# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pmm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('leaders', models.ManyToManyField(related_name='leading_ministries', to='pmm.Member', verbose_name='Lideres')),
                ('members', models.ManyToManyField(related_name='ministries', to='pmm.Member', verbose_name='Miembros')),
            ],
            options={
                'verbose_name': 'Ministerio',
                'verbose_name_plural': 'Ministerios',
                'permissions': (('read_ministry', 'Can read Ministerios'),),
            },
        ),
        migrations.CreateModel(
            name='MinistryObjectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=255, verbose_name='Objetivo')),
                ('ministry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='min.Ministry', verbose_name='Ministerio')),
            ],
            options={
                'verbose_name': 'Objetivo del Ministerio',
                'verbose_name_plural': 'Objetivos del Ministerio',
                'permissions': (('read_ministryobjectives', 'Can read Objetivo del Ministerio'),),
            },
        ),
    ]
