# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('min', '0002_auto_20180604_0501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministry',
            options={'permissions': (('read_ministry', 'Can read Ministries'),), 'verbose_name': 'Ministry', 'verbose_name_plural': 'Ministries'},
        ),
        migrations.AlterModelOptions(
            name='ministryobjective',
            options={'permissions': (('read_ministryobjective', 'Can read Ministry Objective'),), 'verbose_name': 'Ministry Objective', 'verbose_name_plural': 'Ministry Objectives'},
        ),
        migrations.AlterField(
            model_name='ministry',
            name='leaders',
            field=models.ManyToManyField(related_name='leading_ministries', to='pmm.Member', verbose_name='Leaders'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='members',
            field=models.ManyToManyField(related_name='ministries', to='pmm.Member', verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='ministryobjective',
            name='ministry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='min.Ministry', verbose_name='Ministry'),
        ),
        migrations.AlterField(
            model_name='ministryobjective',
            name='objective',
            field=models.CharField(max_length=255, verbose_name='Objective'),
        ),
    ]
