# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmm', '0003_auto_20180425_0504'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pmm.Member', verbose_name='Dueño'),
            preserve_default=False,
        ),
    ]
