# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-20 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('core', '0002_auto_20180605_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, verbose_name='Route')),
                ('groups', models.ManyToManyField(to='auth.Group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'UI Route',
                'verbose_name_plural': 'UI Routes',
            },
        ),
    ]
