# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-20 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uiroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uiroute',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Group'),
        ),
    ]
