# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-23 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180620_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uiroute',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='uiroutes', to='auth.Group', verbose_name='Group'),
        ),
    ]
