# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-30 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180623_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiroute',
            name='parent',
            field=models.CharField(blank=True, max_length=50, verbose_name='Parent Route'),
        ),
        migrations.AddField(
            model_name='uiroute',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Human Readable Label'),
        ),
    ]
