# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 07:11
from __future__ import unicode_literals

import core.models.custom_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('birthday', models.DateField(null=True, verbose_name='Cumpleaños')),
                ('new_birthday', models.DateField(null=True, verbose_name='Nuevo Nacimiento')),
                ('gender', core.models.custom_fields.FixedCharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Género')),
                ('direction_main', models.CharField(max_length=255, null=True, verbose_name='Dirección principal')),
                ('direction_extra', models.CharField(max_length=255, null=True, verbose_name='Dirección extra')),
                ('baptized', models.BooleanField(verbose_name='Bautizado')),
                ('last_visit', models.DateField(null=True, verbose_name='Ultima Visita')),
                ('civil_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmm.CivilStatus')),
                ('integration_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmm.IntegrationLevel')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmm.Person')),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmm.Occupation')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
