# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 05:20
from __future__ import unicode_literals

import core.models.custom_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmm', '0002_auto_20180522_0516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='civilstatus',
            options={'permissions': (('read_civilstatus', 'Can read Civil Status'),), 'verbose_name': 'Civil Status', 'verbose_name_plural': 'Civil Status'},
        ),
        migrations.AlterModelOptions(
            name='discipleship',
            options={'permissions': (('read_discipleship', 'Can read Discipleship'),), 'verbose_name': 'Discipleship', 'verbose_name_plural': 'Discipleships'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'permissions': (('read_family', 'Can read Family'),), 'verbose_name': 'Family', 'verbose_name_plural': 'Relatives'},
        ),
        migrations.AlterModelOptions(
            name='familyrelationship',
            options={'permissions': (('read_familyrelationship', 'Can read Family Relationship'),), 'verbose_name': 'Family Relationship', 'verbose_name_plural': 'Family Relationships'},
        ),
        migrations.AlterModelOptions(
            name='integrationlevel',
            options={'permissions': (('read_integrationlevel', 'Can read Integration Level'),), 'verbose_name': 'Integration Level', 'verbose_name_plural': 'Integration Levels'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['lesson_number'], 'permissions': (('read_lesson', 'Can read Discipleship Lesson'),), 'verbose_name': 'Discipleship Lesson', 'verbose_name_plural': 'Discipleship Lessons'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': (('read_member', 'Can read Member'),), 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={'permissions': (('read_occupation', 'Can read Occupation'),), 'verbose_name': 'Occupation', 'verbose_name_plural': 'Occupations'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('read_person', 'Can read Person'),), 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='persondiscipleship',
            options={'permissions': (('read_persondiscipleship', 'Can read Person in Discipleship'),), 'verbose_name': 'Person in Discipleship', 'verbose_name_plural': 'People in Discipleship'},
        ),
        migrations.AlterField(
            model_name='family',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='pmm.Person', verbose_name='Relative'),
        ),
        migrations.AlterField(
            model_name='family',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative', to='pmm.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='family',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmm.FamilyRelationship', verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='discipleship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='pmm.Discipleship', verbose_name='Discipleship'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.SmallIntegerField(verbose_name='Lesson Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='person_id',
            field=models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pmm.Person', verbose_name='Person reference'),
        ),
        migrations.AlterField(
            model_name='person',
            name='baptized',
            field=models.BooleanField(default=False, verbose_name='Baptized'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='person',
            name='civil_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmm.CivilStatus', verbose_name='Civil Status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='discipleships',
            field=models.ManyToManyField(through='pmm.PersonDiscipleship', to='pmm.Discipleship', verbose_name='Discipleships'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family',
            field=models.ManyToManyField(through='pmm.Family', to='pmm.Person', verbose_name='Relatives'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=core.models.custom_fields.FixedCharField(choices=[('M', 'Man'), ('W', 'Woman')], default='M', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='integration_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmm.IntegrationLevel', verbose_name='Integration Level'),
        ),
        migrations.AlterField(
            model_name='person',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='pmm.Person', verbose_name='Invited By'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Last Visit'),
        ),
        migrations.AlterField(
            model_name='person',
            name='new_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='New Birthday'),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmm.Occupation', verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='persondiscipleship',
            name='disciple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_disciples', to='pmm.Person', verbose_name='Disciple'),
        ),
        migrations.AlterField(
            model_name='persondiscipleship',
            name='discipleship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_discipleships', to='pmm.Discipleship', verbose_name='Discipleship'),
        ),
        migrations.AlterField(
            model_name='persondiscipleship',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Discipleship End Date'),
        ),
        migrations.AlterField(
            model_name='persondiscipleship',
            name='last_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmm.Lesson', verbose_name='Last Lesson'),
        ),
        migrations.AlterField(
            model_name='persondiscipleship',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Discipleship Start Date'),
        ),
        migrations.AlterField(
            model_name='persondiscipleship',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_teachers', to='pmm.Person', verbose_name='Teacher'),
        ),
    ]
