# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmm', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipleship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Discipulado',
                'verbose_name_plural': 'Discipulados',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Familar',
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('discipleship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmm.Discipleship', verbose_name='Discipulado')),
            ],
            options={
                'verbose_name': 'Lección de Discipulado',
                'verbose_name_plural': 'Lecciones de Discipulado',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('information', models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pmm.Person', verbose_name='Información')),
            ],
            options={
                'verbose_name': 'Miembro Pleno',
                'verbose_name_plural': 'Miembros Plenos',
            },
        ),
        migrations.CreateModel(
            name='PersonDiscipleship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True, verbose_name='Fecha de Inicio de Discipulado')),
                ('end_date', models.DateField(null=True, verbose_name='Fecha de Fin de Discipulado')),
            ],
            options={
                'verbose_name': 'Persona en Discipulado',
                'verbose_name_plural': 'Personas en Discipulados',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='civil_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmm.CivilStatus', verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='person',
            name='integration_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmm.IntegrationLevel', verbose_name='Nivel de Integración'),
        ),
        migrations.AlterField(
            model_name='person',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='pmm.Person', verbose_name='Invitado por'),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmm.Occupation', verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='persondiscipleship',
            name='disciple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_disciples', to='pmm.Person', verbose_name='Discipulo'),
        ),
        migrations.AddField(
            model_name='persondiscipleship',
            name='discipleship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_discipleships', to='pmm.Discipleship', verbose_name='Discipulado'),
        ),
        migrations.AddField(
            model_name='persondiscipleship',
            name='last_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmm.Lesson', verbose_name='Última Lección'),
        ),
        migrations.AddField(
            model_name='persondiscipleship',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_teachers', to='pmm.Person', verbose_name='Discipulador'),
        ),
        migrations.AddField(
            model_name='family',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='pmm.Person', verbose_name='Familiar'),
        ),
        migrations.AddField(
            model_name='family',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative', to='pmm.Person', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='family',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmm.FamilyRelationship', verbose_name='Parentezco'),
        ),
        migrations.AddField(
            model_name='person',
            name='discipleships',
            field=models.ManyToManyField(through='pmm.PersonDiscipleship', to='pmm.Discipleship', verbose_name='Discipulados'),
        ),
        migrations.AddField(
            model_name='person',
            name='family',
            field=models.ManyToManyField(through='pmm.Family', to='pmm.Person', verbose_name='Familares'),
        ),
        migrations.AlterUniqueTogether(
            name='persondiscipleship',
            unique_together=set([('disciple', 'discipleship')]),
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together=set([('person', 'family')]),
        ),
    ]
