# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmm', '0003_auto_20180425_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondiscipleship',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de Inicio de Discipulado'),
        ),
    ]
