# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmm', '0004_auto_20180425_0655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persondiscipleship',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='persondiscipleship',
            unique_together=set([]),
        ),
    ]
