# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmm', '0005_auto_20180425_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persondiscipleship',
            options={'verbose_name': 'Persona en Discipulado', 'verbose_name_plural': 'Personas en Discipulados'},
        ),
        migrations.AlterField(
            model_name='persondiscipleship',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Fecha de Inicio de Discipulado'),
        ),
        migrations.AlterUniqueTogether(
            name='persondiscipleship',
            unique_together=set([('disciple', 'discipleship')]),
        ),
    ]
