DROP DATABASE IF EXISTS ibc;
CREATE DATABASE ibc;
USE ibc;

CREATE TABLE ADM_USER(
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50),
    password VARCHAR(64),
    salt VARCHAR(64),
    CONSTRAINT ADM_USER_PK PRIMARY KEY (id)
);

CREATE TABLE ADM_ROLE(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(25) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT ADM_ROLE_PK PRIMARY KEY (id)
);

CREATE TABLE ADM_COMPONENT(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(25) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT ADM_COMPONENT_PK PRIMARY KEY (id)
);

CREATE TABLE ADM_MODEL(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(25) NOT NULL,
    CONSTRAINT ADM_MODEL_PK PRIMARY KEY (id)
);

CREATE TABLE ADM_USER_ROLE(
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    CONSTRAINT ADM_USER_ROLE_PK PRIMARY KEY (user_id, role_id)
);

CREATE TABLE ADM_ROLE_COMPONENT(
    role_id INT NOT NULL,
    component_id INT NOT NULL,
    CONSTRAINT ADM_ROLE_COMPONENT_PK PRIMARY KEY (role_id, component_id)
);

CREATE TABLE ADM_COMPONENT_MODEL(
    component_id INT NOT NULL,
    model_id INT NOT NULL,
    privilege VARCHAR(4),
    CONSTRAINT ADM_COMPONENT_MODEL_PK PRIMARY KEY (component_id, model_id)
);

CREATE TABLE MM_MINITRY(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100),
	description VARCHAR(150),
	CONSTRAINT MM_MINITRY_PK PRIMARY KEY (id)
);


CREATE TABLE MM_MINISTRY_OBJECTIVES(
	id INT NOT NULL AUTO_INCREMENT,
	objective VARCHAR(150) NOT NULL,
	ministry_id INT NOT NULL,
	CONSTRAINT MM_MINISTRY_OBJECTIVES_PK PRIMARY KEY (id)
);

CREATE TABLE MM_MINISTRY_LEADERS(
	ministry_id INT NOT NULL,
	leader_id INT NOT NULL,
	CONSTRAINT MM_MINISTRY_LEADERS_PK PRIMARY KEY (ministry_id, leader_id)
);

CREATE TABLE MM_MINISTRY_TEAM(
	ministry_id INT NOT NULL,
	member_id INT NOT NULL,
	CONSTRAINT MM_MINISTRY_TEAM_PK PRIMARY KEY (ministry_id, member_id)
);


CREATE TABLE RT_HARVEST(
	person_id INT NOT NULL,
	route_id INT NOT NULL,
	discarded BIT(1),
	discarded_reason VARCHAR(100),
	CONSTRAINT RT_HARVEST_PK PRIMARY KEY (person_id)
);

CREATE TABLE RT_COLLABORATOR(
	member_id INT NOT NULL,
	route_id INT NOT NULL,
	ministry_id INT,
	CONSTRAINT RT_COLLABORATOR_PK PRIMARY KEY (member_id)
);

CREATE TABLE RT_VISIT(
	collaborator_id INT NOT NULL,
	harvest_id INT NOT NULL,
	date DATE,
	CONSTRAINT RT_VISIT_PK PRIMARY KEY (collaborator_id, harvest_id)
);

CREATE TABLE RT_ROUTE(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(150),
	direction1 VARCHAR(150),
	direction2 VARCHAR(150),
	zoneMap BLOB,
	leader_id INT,
	CONSTRAINT RT_ROUTE_PK PRIMARY KEY (id)
);

CREATE TABLE PM_PERSON(
	id INT NOT NULL AUTO_INCREMENT,
	firstname VARCHAR(50) NOT NULL,
	lastname VARCHAR(50) NOT NULL,
	birthday DATE,
	new_birthday DATE,
	baptized BIT(1),
	integration_level INT,
	gender Char(1),
	occupation INT,
	civil_status INT,
	last_visit DATE,
	invited_by_id INT,
	direction1 VARCHAR(150),
	direction2 VARCHAR(150),
	CONSTRAINT PM_PERSON_PK PRIMARY KEY (id)
);

CREATE TABLE PM_FAMILY(
	person_id INT NOT NULL,
	family_id INT NOT NULL,
	relationship INT,
	CONSTRAINT PM_FAMILY_PK PRIMARY KEY (person_id, family_id)
);


CREATE TABLE PM_MEMBER(
	person_id INT NOT NULL,
	user_id INT UNIQUE,
	CONSTRAINT PM_MEMBER_PK PRIMARY KEY (person_id)
);

CREATE TABLE PM_DISCIPLESHIP(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(25),
	description VARCHAR(150),
	CONSTRAINT PM_DISCIPLESHIP_PK PRIMARY KEY (id)
);

CREATE TABLE PM_LESSON(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(25),
	description VARCHAR(150),
	discipleship_id INT NOT NULL,
	CONSTRAINT PM_LESSON_PK PRIMARY KEY (id)
);

CREATE TABLE PM_PERSON_DISCIPLESHIP(
	disciple_id INT NOT NULL,
	discipleship_id INT NOT NULL,
	teacher_id INT NOT NULL,
	last_lesson_id INT,
	start_date DATE,
	end_date DATE,
	CONSTRAINT PM_PERSON_DISCIPLESHIP_PK PRIMARY KEY (disciple_id, discipleship_id)
);


-- Lookup Tables --

CREATE TABLE PM_INTEGRATION_LEVEL(
	id INT NOT NULL AUTO_INCREMENT,
	value VARCHAR(20),
	CONSTRAINT PM_INTEGRATION_LEVEL_PK PRIMARY KEY (id)
);

CREATE TABLE PM_OCCUPATION(
	id INT NOT NULL AUTO_INCREMENT,
	value VARCHAR(50),
	CONSTRAINT PM_OCCUPATION_PK PRIMARY KEY (id)
);

CREATE TABLE PM_CIVIL_STATUS(
	id INT NOT NULL AUTO_INCREMENT,
	value VARCHAR(50),
	CONSTRAINT PM_CIVIL_STATUS_LEVEL_PK PRIMARY KEY (id)
);

CREATE TABLE PM_FAMILY_RELATIONSHIP(
	id INT NOT NULL AUTO_INCREMENT,
	value VARCHAR(50),
	CONSTRAINT PM_FAMILY_RELATIONSHIP_PK PRIMARY KEY (id)
);

-- CONSTRAINTS --
ALTER TABLE PM_PERSON ADD CONSTRAINT PM_INVITED_BY_FK FOREIGN KEY (invited_by_id) REFERENCES PM_PERSON(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PM_PERSON ADD CONSTRAINT PM_PERSON_INTEGRATION_LEVEL_FK FOREIGN KEY (integration_level) REFERENCES PM_INTEGRATION_LEVEL(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PM_PERSON ADD CONSTRAINT PM_PERSON_OCCUPATION_FK FOREIGN KEY (occupation) REFERENCES PM_OCCUPATION(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PM_PERSON ADD CONSTRAINT PM_PERSON_CIVIL_STATUS_FK FOREIGN KEY (civil_status) REFERENCES PM_CIVIL_STATUS(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PM_FAMILY ADD CONSTRAINT PM_FAMILY_PERSON_FK FOREIGN KEY (person_id) REFERENCES PM_PERSON(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PM_FAMILY ADD CONSTRAINT PM_FAMILY_FK FOREIGN KEY (family_id) REFERENCES PM_PERSON(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PM_FAMILY ADD CONSTRAINT PM_FAMILY_FAMILY_RELATIONSHIP_FK FOREIGN KEY (relationship) REFERENCES PM_FAMILY_RELATIONSHIP(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE RT_HARVEST ADD CONSTRAINT RT_HARVEST_PERSON_FK FOREIGN KEY (person_id) REFERENCES PM_PERSON(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RT_HARVEST ADD CONSTRAINT RT_HARVEST_ROUTE_FK FOREIGN KEY (route_id) REFERENCES RT_ROUTE(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PM_MEMBER ADD CONSTRAINT PM_MEMBER_PERSON_FK FOREIGN KEY (person_id) REFERENCES PM_PERSON(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PM_MEMBER ADD CONSTRAINT PM_MEMBER_USER_FK FOREIGN KEY (user_id) REFERENCES ADM_USER(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE RT_COLLABORATOR ADD CONSTRAINT RT_COLLABORATOR_MEMBER_FK FOREIGN KEY (member_id) REFERENCES PM_MEMBER(person_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RT_COLLABORATOR ADD CONSTRAINT RT_COLLABORATOR_ROUTE_FK FOREIGN KEY (route_id) REFERENCES RT_ROUTE(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RT_COLLABORATOR ADD CONSTRAINT RT_COLLABORATOR_MINISTRY_FK FOREIGN KEY (ministry_id) REFERENCES MM_MINITRY(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RT_COLLABORATOR ADD CONSTRAINT RT_COLLABORATOR_ROUTE_UQ UNIQUE(route_id);
ALTER TABLE RT_COLLABORATOR ADD CONSTRAINT RT_COLLABORATOR_MINISTRY_UQ UNIQUE(ministry_id);

ALTER TABLE RT_VISIT ADD CONSTRAINT RT_VISIT_COLLABORATOR_FK FOREIGN KEY (collaborator_id) REFERENCES RT_COLLABORATOR(member_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RT_VISIT ADD CONSTRAINT RT_VISIT_HARVEST_FK FOREIGN KEY (harvest_id) REFERENCES RT_HARVEST(person_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE RT_ROUTE ADD CONSTRAINT RT_ROUTE_COLLABORATOR_FK FOREIGN KEY (leader_id) REFERENCES RT_COLLABORATOR(member_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RT_ROUTE ADD CONSTRAINT RT_ROUTE_COLLABORATOR_UQ UNIQUE(leader_id);

ALTER TABLE MM_MINISTRY_OBJECTIVES ADD CONSTRAINT MM_MINISTRY_OBJECTIVES_MINISTRY_FK FOREIGN KEY (ministry_id) REFERENCES MM_MINITRY(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE MM_MINISTRY_LEADERS ADD CONSTRAINT MM_MINISTRY_LEADERS_MINISTRY_FK FOREIGN KEY (ministry_id) REFERENCES MM_MINITRY(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE MM_MINISTRY_LEADERS ADD CONSTRAINT MM_MINISTRY_LEADERS_MEMBER_FK FOREIGN KEY (leader_id) REFERENCES PM_MEMBER(person_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE MM_MINISTRY_TEAM ADD CONSTRAINT MM_MINISTRY_TEAM_MINISTRY_FK FOREIGN KEY (ministry_id) REFERENCES MM_MINITRY(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE MM_MINISTRY_TEAM ADD CONSTRAINT MM_MINISTRY_TEAM_MEMBER_FK FOREIGN KEY (member_id) REFERENCES PM_MEMBER(person_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PM_LESSON ADD CONSTRAINT PM_LESSON_DISCIPLESHIP_FK FOREIGN KEY (discipleship_id) REFERENCES PM_DISCIPLESHIP(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PM_PERSON_DISCIPLESHIP ADD CONSTRAINT PM_PERSON_DISCIPLESHIP_DISCIPLE_FK FOREIGN KEY (disciple_id) REFERENCES PM_PERSON(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PM_PERSON_DISCIPLESHIP ADD CONSTRAINT PM_PERSON_DISCIPLESHIP_DISCIPLESHIP_FK FOREIGN KEY (discipleship_id) REFERENCES PM_DISCIPLESHIP(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PM_PERSON_DISCIPLESHIP ADD CONSTRAINT PM_PERSON_DISCIPLESHIP_TEACHER_FK FOREIGN KEY (teacher_id) REFERENCES PM_PERSON(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PM_PERSON_DISCIPLESHIP ADD CONSTRAINT PM_PERSON_DISCIPLESHIP_LESSON_FK FOREIGN KEY (last_lesson_id) REFERENCES PM_LESSON(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ADM_USER ADD CONSTRAINT ADM_USERNAME_UQ UNIQUE(username);

ALTER TABLE ADM_USER_ROLE ADD CONSTRAINT ADM_USER_ROLE_USER_FK FOREIGN KEY (user_id) REFERENCES ADM_USER(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ADM_USER_ROLE ADD CONSTRAINT ADM_USER_ROLE_ROLE_FK FOREIGN KEY (role_id) REFERENCES ADM_ROLE(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ADM_ROLE_COMPONENT ADD CONSTRAINT ADM_ROLE_COMPONENT_ROLE_FK FOREIGN KEY (role_id) REFERENCES ADM_ROLE(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ADM_ROLE_COMPONENT ADD CONSTRAINT ADM_ROLE_COMPONENT_COMPONENT_FK FOREIGN KEY (component_id) REFERENCES ADM_COMPONENT(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ADM_COMPONENT_MODEL ADD CONSTRAINT ADM_COMPONENT_MODEL_COMPONENT_FK FOREIGN KEY (component_id) REFERENCES ADM_COMPONENT(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ADM_COMPONENT_MODEL ADD CONSTRAINT ADM_COMPONENT_MODEL_MODEL_FK FOREIGN KEY (model_id) REFERENCES ADM_MODEL(id) ON DELETE CASCADE ON UPDATE CASCADE;

-- DML for Lookup Tables --
INSERT INTO PM_INTEGRATION_LEVEL(value) VALUES ('Unido Recientemente');
INSERT INTO PM_INTEGRATION_LEVEL(value) VALUES ('Integrado');
INSERT INTO PM_INTEGRATION_LEVEL(value) VALUES ('Inconstante');
INSERT INTO PM_INTEGRATION_LEVEL(value) VALUES ('Retirado');

INSERT INTO PM_OCCUPATION(value) VALUES ('Estudiante Primaria');
INSERT INTO PM_OCCUPATION(value) VALUES ('Estudiante Secundaria');
INSERT INTO PM_OCCUPATION(value) VALUES ('Estudiante Universitario');
INSERT INTO PM_OCCUPATION(value) VALUES ('Empleado');
INSERT INTO PM_OCCUPATION(value) VALUES ('En Busca de Empleo');
INSERT INTO PM_OCCUPATION(value) VALUES ('Otros');

INSERT INTO PM_CIVIL_STATUS(value) VALUES ('Soltero(a)');
INSERT INTO PM_CIVIL_STATUS(value) VALUES ('Casado(a)');
INSERT INTO PM_CIVIL_STATUS(value) VALUES ('Divorciado(a)');
INSERT INTO PM_CIVIL_STATUS(value) VALUES ('Viudo(a)');
INSERT INTO PM_CIVIL_STATUS(value) VALUES ('Unión Libre');

INSERT INTO PM_FAMILY_RELATIONSHIP(value) VALUES ('Esposo(a)');
INSERT INTO PM_FAMILY_RELATIONSHIP(value) VALUES ('Hijo(a)');
INSERT INTO PM_FAMILY_RELATIONSHIP(value) VALUES ('Mamá');
INSERT INTO PM_FAMILY_RELATIONSHIP(value) VALUES ('Papá');
INSERT INTO PM_FAMILY_RELATIONSHIP(value) VALUES ('Abuelo(a)');
INSERT INTO PM_FAMILY_RELATIONSHIP(value) VALUES ('Nieto(a)');
INSERT INTO PM_FAMILY_RELATIONSHIP(value) VALUES ('Tío(a)');
INSERT INTO PM_FAMILY_RELATIONSHIP(value) VALUES ('Primo(a)');
INSERT INTO PM_FAMILY_RELATIONSHIP(value) VALUES ('Otro');
