# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('min', '0001_initial'),
        ('pmm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('member_information', models.OneToOneField(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pmm.Member', verbose_name='Información de Colaborador')),
                ('route_captain', models.BooleanField(default=False, verbose_name='Es Capitan')),
                ('ministry', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='min.Ministry', verbose_name='Ministerio')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('information', models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pmm.Person', verbose_name='Información')),
                ('discarded', models.BooleanField(default=False, verbose_name='Descartado')),
                ('discarded_reason', models.CharField(max_length=255, null=True, verbose_name='¿Por qué fue descartado?')),
            ],
            options={
                'verbose_name': 'Mies',
                'verbose_name_plural': 'Mies',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('direction_main', models.CharField(max_length=255, verbose_name='Dirección principal')),
                ('direction_extra', models.CharField(max_length=255, null=True, verbose_name='Dirección extra')),
                ('zoneMap', models.ImageField(max_length=255, upload_to='images/route/', verbose_name='Miembros')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Visita')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rte.Collaborator', verbose_name='Colaborador')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rte.Harvest', verbose_name='Mies')),
            ],
            options={
                'verbose_name': 'Visita Realizada',
                'verbose_name_plural': 'Visitas Realizadas',
            },
        ),
        migrations.AddField(
            model_name='harvest',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rte.Route', verbose_name='Ruta'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='visits',
            field=models.ManyToManyField(through='rte.Visit', to='rte.Collaborator', verbose_name='Visitas'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rte.Route', verbose_name='Ruta'),
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together=set([('collaborator', 'harvest')]),
        ),
    ]
