# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='zoneMap',
            new_name='zone_map',
        ),
    ]
