# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rte', '0002_auto_20180601_0458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborator',
            options={'permissions': (('read_collaborator', 'Can read Collaborator'),), 'verbose_name': 'Collaborator', 'verbose_name_plural': 'Collaborators'},
        ),
        migrations.AlterModelOptions(
            name='harvest',
            options={'permissions': (('read_harvest', 'Can read Harvest'),), 'verbose_name': 'Harvest', 'verbose_name_plural': 'Harvests'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'permissions': (('read_route', 'Can read Route'),), 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'permissions': (('read_visit', 'Can read Visit'),), 'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='member_id',
            field=models.OneToOneField(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pmm.Member', verbose_name='Member reference'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='ministry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='min.Ministry', verbose_name='Ministry'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rte.Route', verbose_name='Route'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='route_captain',
            field=models.BooleanField(default=False, verbose_name='Is captain'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='discarded',
            field=models.BooleanField(default=False, verbose_name='Discarded'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='discarded_reason',
            field=models.CharField(max_length=255, null=True, verbose_name='Discarded Reason'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='person_id',
            field=models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pmm.Person', verbose_name='Person reference'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rte.Route', verbose_name='Route'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='visits',
            field=models.ManyToManyField(through='rte.Visit', to='rte.Collaborator', verbose_name='Visits'),
        ),
        migrations.AlterField(
            model_name='route',
            name='zone_map',
            field=models.ImageField(max_length=255, upload_to='images/route/', verbose_name='Map Zone'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rte.Collaborator', verbose_name='Collaborator'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Visit date'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='harvest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rte.Harvest', verbose_name='Harvest'),
        ),
    ]
